name: Terraform CI

on:
  pull_request:
    branches: ["main"]

jobs:
  terraform-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        working-directory: ./Networking
        run: terraform init -backend=false

      - name: Terraform Validate
        working-directory: ./Networking
        run: terraform validate
